### ISSUE TITLE
Is this plugin integrating with some other LP software?

### ISSUE THREAD

**Issue by akkartik** [jbyuki/ntangle.vim#2]
Is it true that there's no other tangler needed? It's just the Vim plugin emitting tangled output? So for example if I created a repo that used this system and didn't check in the generated files, someone cloning the repo would have to first generate them by opening up the .tl file and typing `:wq`?

**Comment by jbyuki** [comment]
I'm not sure to fully undertand the question. What do you mean by other LP software? ntangle.vim is meant to be used standalone (as a VIM plugin). The usual process involves writing LP code and then on save, it will generate the "tangled" output, by default in the "tangle/" folder. I've used it in several of my projects (see [instant.nvim](https://github.com/jbyuki/instant.nvim/tree/master/src)) where I usually both distribute the source and the generated files. I find it to be the easiest.
For convenience regarding your question, I also have the :TangleAll command which will tangle all files in the current directory.

**Comment by akkartik** [comment]
Thank you, that completely answers my question.
